# Generated by Django 6.0.7 on 2026-07-22 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ENGINE_OIL', 'Engine Oil'), ('GEARBOX_OIL', 'Gearbox Oil'), ('BRAKE_FLUID', 'Brake Fluid'), ('OIL_FILTER', 'Oil Filter'), ('OTHER_FILTER', 'Other Filter'), ('BRAKE_PADS', 'Brake Pads'), ('MISC', 'Miscellaneous Part')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_senior', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('SMALL', 'Small Car'), ('COMMERCIAL', 'Commercial Car'), ('HEAVY', 'Heavy Vehicle')], default='SMALL', max_length=20)),
                ('make_model', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='bay.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('labour_charge', models.DecimalField(decimal_places=2, default=20000.0, max_digits=10)),
                ('wheel_alignment', models.BooleanField(default=False)),
                ('wheel_balancing', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'In Service Bay'), ('COMPLETED', 'Completed'), ('PAID', 'Paid & Released')], default='PENDING', max_length=15)),
                ('assigned_technicians', models.ManyToManyField(related_name='service_jobs', to='bay.technician')),
                ('senior_technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_jobs', to='bay.technician')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='bay.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VisitPartUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bay.part')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='bay.servicevisit')),
            ],
        ),
    ]
