# Generated by Django 6.0.7 on 2026-07-22 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bay', '0002_remove_customer_created_at_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevisit',
            name='ac_servicing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='brake_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='computer_diagnostics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='issue_description',
            field=models.TextField(blank=True, help_text="Describe the problem, or state if unsure what's wrong.", null=True),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='oil_change_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='suspension_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='transport_choice',
            field=models.CharField(choices=[('CUSTOMER_BRINGING', 'Customer will bring car to service bay'), ('BAY_PICKUP_TOW', 'Service bay to fix/tow from current location')], default='CUSTOMER_BRINGING', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicevisit',
            name='assigned_technicians',
            field=models.ManyToManyField(blank=True, related_name='service_jobs', to='bay.technician'),
        ),
        migrations.AlterField(
            model_name='servicevisit',
            name='senior_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_jobs', to='bay.technician'),
        ),
        migrations.AlterField(
            model_name='servicevisit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'In Service Bay'), ('LOGISTICS_PENDING', 'Pending Pickup/Arrival'), ('COMPLETED', 'Completed'), ('PAID', 'Paid & Released')], default='PENDING', max_length=30),
        ),
    ]
